package ethertest

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

// Independent oracle: these bytes and roots are generated by the pinned Python
// ethereum/ssz-specs implementation, never by this Go encoder.
func TestGloasReferenceVectors(t *testing.T) {
	data, err := os.ReadFile("testdata/vectors/gloas/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vectors []struct {
		Name string
		Data json.RawMessage
		SSZ  hexutil.Bytes
		Root common.Hash
	}
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatal(err)
	}
	for _, vector := range vectors {
		t.Run(vector.Name, func(t *testing.T) {
			var value any
			switch vector.Name {
			case "requests":
				value = new(executionRequests)
			case "payload":
				value = new(gloasExecutionPayload)
			case "bid":
				value = new(gloasPayloadBid)
			case "envelope":
				value = new(gloasSignedPayloadEnvelope)
			case "block":
				value = new(gloasSignedBeaconBlock)
			case "column":
				value = new(gloasDataColumn)
			default:
				t.Fatal("unknown vector")
			}
			if err := json.Unmarshal(vector.Data, value); err != nil {
				t.Fatal(err)
			}
			encoded, err := gloasSSZ.MarshalSSZ(value)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(encoded, vector.SSZ) {
				t.Fatalf("SSZ differs from independent reference: got %d bytes, want %d", len(encoded), len(vector.SSZ))
			}
			root, err := gloasSSZ.HashTreeRoot(value)
			if err != nil {
				t.Fatal(err)
			}
			if common.Hash(root) != vector.Root {
				t.Fatalf("root %x, want %x", root, vector.Root)
			}
			if err := gloasSSZ.UnmarshalSSZ(value, vector.SSZ); err != nil {
				t.Fatal(err)
			}
			root, err = gloasSSZ.HashTreeRoot(value)
			if err != nil || common.Hash(root) != vector.Root {
				t.Fatalf("decode root mismatch: %v", err)
			}
		})
	}
}
